config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]
  
  resources :ideas do
    resources :comments, only:[:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :members, only: [:create, :destroy]
  end

  resources :users

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

   root 'ideas#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :like_user, through: :likes, source: :user

  has_many :members, dependent: :destroy
  has_many :user_members, through: :members, source: :user

  has_many :comments, dependent: :destroy

  validates :title, presence: true, uniqueness: {scope: :body}
  validates :body, presence:true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/


  def is_liked_by (user)
    likes.find_by_user_id user
  end

  def has_member (user)
    members.find_by_user_id user
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :find_idea, only:[:show, :destroy, :update, :edit]
  def index
    @ideas = Idea.all.order("updated_at")
  end

  def show
    @comments = @idea.comments
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      redirect_to @idea, notice:"Idea created successfully"

    else
      flash[:alert] = "Idea is not created. Try again"
      render :new
    end


  end

  def update
    if @idea.update idea_params
      redirect_to @idea, notice:"Update success"
    else
      flash[:alert] = "Update failed"
      render :edit
    end
  end

  def destroy
    if user_signed_in?
      @idea = current_user.ideas.find params[:id]
      @idea.destroy
      redirect_to ideas_path, notice: "idea deleted."
    else
      redirect_to new_session_path, alert:"you must sign in before deleting an idea"
    end
  end

  private
  def idea_params
    params.require(:idea).permit(:title, :body, :avatar)
  end

  def find_idea
    @idea = Idea.find params[:id]
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<div>

  <% if @idea.errors %>
  <div>
    <%= @idea.errors.full_messages.join(",") %>
  </div>
  <% end %>

  <%= form_for @idea do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.file_field :avatar %>
  </div>

  <%= f.submit %>
  <% end %>
</div>

app/views/ideas/edit.html.erb
<div class="container">

  <h1>Update Idea</h1>

  <%= render "form" %>
</div>

app/views/ideas/index.html.erb
<div class="container">
  <h1>All Ideas</h1>

  <table class="table table-striped">
    <% @ideas.each do |idea| %>
    <tr>
      <td><span style="font-size: 20px;"><%= link_to idea.title, idea_path(idea) %></span>
        <br> <h4><%= idea.body %></h4>
        <br> Posted by <%= idea.user.full_name %> <br>

        <% like = idea.is_liked_by(current_user) %>
        <% if like %>
        <%= link_to fa_icon("thumbs-up"), idea_like_path(idea, like), method: :delete, class: "like-fav-icon"  %>
        <% else %>
        <%= link_to fa_icon("thumbs-o-up"), idea_likes_path(idea), method: :post, class: "like-fav-icon" %>
        <% end %>

        <span class="badge"><%= idea.likes.count %></span>

        <% member = idea.has_member(current_user) %>
        <% if member %>
        <%= link_to fa_icon("user-times"), idea_member_path(idea, member), method: :delete, class: "like-fav-icon"  %>
        <% else %>
        <%= link_to fa_icon("user-plus"), idea_members_path(idea), method: :post, class: "like-fav-icon" %>
        <% end %>
        <span class="badge"><%= idea.members.count %></span>

      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/ideas/new.html.erb
<div class="container">

  <h1>New Idea</h1>

  <%= render "form" %>
</div>

app/views/ideas/show.html.erb
<div class="container">

  <h2>Idea: <%= @idea.title %></h2>
  <p><%= @idea.body %></p>
  <%= image_tag @idea.avatar.url(:medium) %>

  <p>Created by: <%= link_to @idea.user.full_name, user_path(@idea.user) %></p>

  <div>
    <% if can? :manage, @idea %>
    <%= link_to "Edit", edit_idea_path(@idea), class:"btn btn-default btn-xs" %>
    <%= link_to "Delete", idea_path(@idea), method: :delete, class:"btn btn-default btn-xs" %>
    <% end %>
    <% like = @idea.is_liked_by(current_user) %>
    <% if like %>
    <%= link_to fa_icon("thumbs-up"), idea_like_path(@idea, like), method: :delete, class: "like-fav-icon"  %>
    <% else %>
    <%= link_to fa_icon("thumbs-o-up"), idea_likes_path(@idea), method: :post, class: "like-fav-icon" %>
    <% end %>
    <span class="badge"><%= @idea.likes.count %></span>

    <% member = @idea.has_member(current_user) %>
    <% if member %>
    <%= link_to fa_icon("user-times"), idea_member_path(@idea, member), method: :delete, class: "like-fav-icon"  %>
    <% else %>
    <%= link_to fa_icon("user-plus"), idea_members_path(@idea), method: :post, class: "like-fav-icon" %>
    <% end %>
    <%= @idea.user_members.all.map{|m| m.full_name}.join(", ") %>
    <span class="badge"><%= @idea.members.count %></span>
  </div>
  <hr />

  <div class="comments-container">
    <div class="comments">
      <% if @comments.size > 0 %>
      <ul>
        <% @comments.each do |x| %>
        <li><%= x[:body] %> <br>
          <%= x[:created_at] %> by <%=link_to x.user.full_name, user_path(x.user) %>
          <% if can? :destroy, x %>
          <%= link_to "Delete", idea_comment_path(@idea, x), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-default btn-xs"%>
          <% end %>
        </li>
        <% end %>
      </ul>
      <% end %>
    </div>

    <div class="comments">
      <% if user_signed_in? %>
      <%= form_for [@idea, Comment.new] do |f|  %>
      <div class="form-group">
        <%= f.label :body, value="Comment" %><br/>
        <%= f.text_area :body , class: "form-control", id: "comment-textarea", rows: "3" %>
      </div>
      <div class="form-group">
        <%= f.submit class:"btn btn-info" %>
      </div>
      <% end %>
      <% else %>
      <%= link_to "Log in", new_session_path %> to leave a comment!</div>
      <% end %>
    </div>


  </div>